### ISSUE TITLE
knob not draggable . 

### ISSUE THREAD

**Issue by sap9433** [whoisandie/react-rangeslider#1]
Though onChange function is getting called and value is geeting updated but knob is fixed at init position.

using ES6 and react 0.13
```
...
...
<Slider onChange={this.handleChange.bind(this, inp.id)} />
...
```

**Comment by sap9433** [comment]
Your npm package also doesn't contain necessary css , so I had to copy it from demo page source-code.

**Comment by styrmis** [comment]
Just hit the same CSS issue myself.

To get the knob to update, you need to set `value` property in the JSX, i.e. 

```
<Slider value={this.state.sliderValue} onChange={this.handleChange.bind(this, inp.id)} />
```

That worked for me, but something about it doesn't seem quite right.

**Comment by whoisandie** [comment]
@sap9433 @styrmis yes, just to decouple the styles outta the component, styles have been isolated out. Styles shouldn't  be tightly coupled, checkout the docs for more info on styles.
