### ISSUE TITLE
Version 1.0.1 published on npm doesn't include lib/index

### ISSUE THREAD

**Issue by joshfarrant** [whoisandie/react-rangeslider#11]
Version 1.0.1 doesn't appear to contain all the necessary files.

If I install react-rangeslider through npm and inspect the files in `node_modules/react-rangeslider` I only see the following files/directories.

- index.html
- LICENSE
- node_modules/
- .npmignore
- package.json
- README.md
- tests/

Judging by the `main` line in your [package.json](https://github.com/whoisandie/react-rangeslider/blob/master/package.json#L5) I'd expect that there should at least be a lib/ directory containing the built/bundled code. Is this the case?

**Comment by lprajus2007** [comment]
+1 I'm experiencing this issue too

**Comment by aaronkw** [comment]
+1

**Comment by whoisandie** [comment]
@joshfarrant @lprajus2007 @aaronkw Sorry guys, must have accidentally published it. Fixing it right away.
