### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by rahul-budhia** [whoisandie/react-rangeslider#15]
On including **Slider** like shown in **ES6** example. It throws following error:

invariant.js:39 Uncaught **Invariant Violation**: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

I am using **react v0.14.8**

Is anyone facing the same issue?

**Comment by pietgit** [comment]
Hey, I'm facing the (exact) same error - react 0.14.7

**Comment by messutied-pf** [comment]
Also getting this error :(

**Comment by mygoare** [comment]
Seems I made a duplicate issue, see #19 .

I met the same error, I think the solution is declaring the peerDependencies in `package.json` file

**Comment by scottjason** [comment]
+ 1

**Comment by HuaGuoFeng** [comment]
ddd
