### ISSUE TITLE
This component can not work, unless resize the window after mount

### ISSUE THREAD

**Issue by benbush** [whoisandie/react-rangeslider#24]
This component can not work, unless resize the window after mount

**Comment by zombler** [comment]
@benbush did you find a solution to this?

**Comment by martinpesout** [comment]
Solution is in `master` branch but it's not included under current tag: v1.0.3

Is it possible to prepare new version 1.0.4 which will have this https://github.com/whoisandie/react-rangeslider/commit/44da62ce03042de6a1e45082a4b3c0b53cbb1f8f#commitcomment-18879131 included?

**Comment by whoisandie** [comment]
@benbush @zombler @martinpesout https://github.com/whoisandie/react-rangeslider/commit/33db2519633262ed7078495d13601c3fcaffb7bb fixes this 👍
