### ISSUE TITLE
Custom label function?

### ISSUE THREAD

**Issue by FezVrasta** [whoisandie/react-rangeslider#28]
I'd like to show a custom label based on the value of the slider.

For example, my slider uses unix time stamps, and I want to show dates. Can I do this?

**Comment by MarkRabey** [comment]
I've made fork and started working on this. I'll keep you posted!

**Comment by MarkRabey** [comment]
@FezVrasta until #34 is accepted, you can try my fork here: https://github.com/Opentrace/react-rangeslider

**Comment by FezVrasta** [comment]
Thanks, I used it just for a small side project so I don't really need it anymore.
