### ISSUE TITLE
Doesn't Return React Component?

### ISSUE THREAD

**Issue by bradynapier** [whoisandie/react-rangeslider#3]
Warning: Slider(...): React component classes must extend React.Component.warning @ 
Uncaught Error: Invariant Violation: Slider.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

Apparently this doesnt work?

**Comment by nunobbras** [comment]
the same

**Comment by whoisandie** [comment]
@bradynapier @nunobbras The slider isn't compatible with react 0.14 yet, still a wip. Should be up this week.

**Comment by nunobbras** [comment]
thanks @whoisandie.

**Comment by wision** [comment]
@whoisandie how does it look with 0.14 support?

**Comment by jesperwiner** [comment]
+1   0.14.x support ?

**Comment by ralphholzmann** [comment]
just running into this now too

**Comment by aaronkw** [comment]
+1

**Comment by wid** [comment]
+1

**Comment by alexandreferreirafr** [comment]
+1

**Comment by jamesfzhang** [comment]
Any updates on this? Thanks.

**Comment by gabadi** [comment]
+1

**Comment by vlain** [comment]
+1

**Comment by micros123** [comment]
There's a pull request waiting. Can you just merge it and make everyone happy? :-)

**Comment by gavinkilbride** [comment]
+1

**Comment by kambanwait** [comment]
Any chance that anyone has been able to make this work without the pull request?

**Comment by alexykot** [comment]
+1

**Comment by beinarovic** [comment]
Same issue...

**Comment by joshfarrant** [comment]
@whoisandie Still no movement on this? It's a pretty simple [PR](https://github.com/whoisandie/react-rangeslider/pull/7), can it not just be merged in and this issue closed?
