### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./rangeslider.less

### ISSUE THREAD

**Issue by tomoberry** [whoisandie/react-rangeslider#43]
Hi, I am installing your module with:

```
npm install react-rangeslider --save
```

But when I try to do:
```
import Slider from 'react-rangeslider';
```

I see the following error:  
```
ERROR in ./~/react-rangeslider/lib/Rangeslider.js
watch_1         | Module not found: Error: Cannot resolve 'file' or 'directory' ./rangeslider.less in /node_modules/react-rangeslider/lib
```

looks like the module tries to require('./rangeslider.less') from node_modules/react-rangeslider/lib but rangeslider.less does not seem to get installed with the package.

**Comment by sashakru** [comment]
Same issue

**Comment by dnish** [comment]
Same problem here within our Meteor application.

**Comment by milocosmopolitan** [comment]
same issue. I feel like last npm published version is not identical to current github repo.
Quick workaround was uncomment node_modules/react-rangeslider require('./rangeslider.less') and have rangeslider.less file content on my own stylesheet
