### ISSUE TITLE
Errors - React component classes must extend React.Component.

### ISSUE THREAD

**Issue by foodaka** [whoisandie/react-rangeslider#5]
Out of the box getting errors, any idea how to fix this? Is it required that i use es6?

also getting this error

Uncaught Invariant Violation: Slider.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

var React  = require('react');
var Slider = require('react-rangeslider');

var Volume = React.createClass({
    getInitialState: function(){
        return {
            value: 10,
        };
    },
    handleChange: function(value) {
        this.setState({
            value: value,
        });
    },
    render: function() {
        return (
            <Slider value={this.state.value} orientation="vertical" onChange={this.handleChange} />
        );
    }
});

module.exports = Volume;

**Comment by Wilfredfury** [comment]
this repo is dead for weeks, the error you are getting is because of react 14+.
we've switched to https://www.npmjs.com/package/react-slider pretty easily.

**Comment by foodaka** [comment]
k tks for the prompt response
